"""Custom Bazel rules for building PIC blobs as shared objects.

The blob pipeline is:
  1. cc_library      -> object files (.a archive)
  2. pic_blob_link   -> .so (shared object with custom linker script)
  3. blob_stage      -> copies .so into python/picblobs/_blobs/{os}/{arch}/

The link step is a private rule that invokes the resolved C/C++ toolchain's
linker directly. This preserves the unstripped sections that cc_binary removes
while keeping compiler/linker binaries declared as Bazel inputs for remote
execution.
"""

load("@rules_cc//cc:action_names.bzl", "ACTION_NAMES")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_cc//cc:find_cc_toolchain.bzl", "find_cc_toolchain", "use_cc_toolchain")
load("@rules_cc//cc/common:cc_common.bzl", "cc_common")
load("//bazel:platforms.bzl", "BLOB_TARGETS")  # @unused (re-exported)

# Re-export BLOB_TARGETS from the generated platforms.bzl so existing
# consumers of blob.bzl continue to work. The canonical source is
# bazel/platforms.bzl (generated by tools/generate.py from registry.py).

# Attribute names that are legal on both cc_library and the private link rule.
# Anything in **kwargs that isn't in this set is routed only to cc_library.
_SHARED_KWARGS = (
    "tags",
    "visibility",
    "testonly",
    "compatible_with",
    "target_compatible_with",
    "exec_compatible_with",
    "restricted_to",
    "features",
)

def _split_kwargs(kwargs):
    """Return (shared_kwargs, library_only_kwargs)."""
    shared = {}
    library_only = {}
    for key, value in kwargs.items():
        if key in _SHARED_KWARGS:
            shared[key] = value
        else:
            library_only[key] = value
    return shared, library_only

def _target_os_defines():
    """Return per-target-OS compile defines selected from platform constraints."""
    return select({
        "//platforms:is_target_linux": ["PICBLOBS_OS_LINUX"],
        "//platforms:is_target_freebsd": ["PICBLOBS_OS_FREEBSD"],
        "//platforms:is_target_windows": ["PICBLOBS_OS_WINDOWS"],
        "//conditions:default": [],
    })

def _target_abi_copts():
    """Return ABI-specific compile flags selected from platform constraints."""
    return select({
        "//platforms:is_target_windows_aarch64": ["-ffixed-x18"],
        "//conditions:default": [],
    })

# Link flags equivalent to the toolchain's `freestanding` feature flag_set
# for link actions. Kept in sync with toolchains/bootlin.bzl and
# toolchains/arm_none_eabi.bzl.
_FREESTANDING_LINK_FLAGS = [
    "-nostdlib",
    "-nostartfiles",
    "-Wl,--gc-sections",
]

def _pic_blob_link_impl(ctx):
    cc_toolchain = find_cc_toolchain(ctx)
    feature_configuration = cc_common.configure_features(
        ctx = ctx,
        cc_toolchain = cc_toolchain,
        requested_features = ctx.features,
        unsupported_features = ctx.disabled_features,
    )
    linker = cc_common.get_tool_for_action(
        feature_configuration = feature_configuration,
        action_name = ACTION_NAMES.cpp_link_dynamic_library,
    )

    out = ctx.actions.declare_file(ctx.label.name + ".so")
    args = ctx.actions.args()
    args.add_all(ctx.attr.link_mode_flags)
    if ctx.file.linker_script:
        args.add("-T" + ctx.file.linker_script.path)
    args.add("-Wl,--whole-archive")
    args.add(ctx.file.archive)
    args.add("-Wl,--no-whole-archive")
    args.add_all(ctx.attr.linkopts)
    args.add_all(ctx.attr.runtime_libs)
    args.add("-o")
    args.add(out)

    inputs = [ctx.file.archive]
    if ctx.file.linker_script:
        inputs.append(ctx.file.linker_script)

    ctx.actions.run(
        executable = linker,
        arguments = [args],
        inputs = depset(inputs, transitive = [cc_toolchain.all_files]),
        outputs = [out],
        mnemonic = "PicBlobLink",
        progress_message = "Linking PIC blob %{label}",
        tools = cc_toolchain.all_files,
    )
    return [DefaultInfo(files = depset([out]))]

_pic_blob_link = rule(
    implementation = _pic_blob_link_impl,
    attrs = {
        "archive": attr.label(
            allow_single_file = True,
            mandatory = True,
        ),
        "linker_script": attr.label(
            allow_single_file = True,
        ),
        "linkopts": attr.string_list(),
        "link_mode_flags": attr.string_list(
            default = ["-shared"],
        ),
        "runtime_libs": attr.string_list(),
    },
    fragments = ["cpp"],
    toolchains = use_cc_toolchain(),
)

def pic_blob(
        name,
        srcs,
        deps = None,
        hdrs = None,
        linker_script = None,
        copts = None,
        local_defines = None,
        linkopts = None,
        **kwargs):
    """Compile and link a PIC blob as a shared object.

    Creates:
      - {name}_obj : cc_library with the blob source
      - {name}     : private rule that links the .so

    Args:
        name: Blob type name (e.g., "hello", "alloc_jump").
        srcs: C source files.
        deps: cc_library dependencies.
        hdrs: Header files.
        linker_script: Label for the custom linker script.
        copts: Additional C compiler flags.
        local_defines: Preprocessor defines (e.g., ["PIC_PLATFORM_HOSTED"]).
        linkopts: Additional linker flags (added to the link command).
        **kwargs: Common attributes (tags, visibility, etc.) forwarded to
            both the cc_library and the link rule. Anything that is not a
            shared attribute is routed only to the cc_library.
    """
    deps = deps or []
    hdrs = hdrs or []
    copts = (copts or []) + _target_abi_copts()
    local_defines = (local_defines or []) + _target_os_defines()
    linkopts = linkopts or []
    lib_name = name + "_obj"

    shared_kwargs, library_kwargs = _split_kwargs(kwargs)

    cc_library(
        name = lib_name,
        srcs = srcs,
        hdrs = hdrs,
        copts = copts,
        local_defines = local_defines,
        deps = deps,
        **dict(shared_kwargs, **library_kwargs)
    )

    # PPC32 blobs work reliably as static relocatable ELFs. The old shell link
    # discovered this by running `$(CC) -dumpmachine`; keep it declarative so
    # remote workers see the same action key as local builds.
    link_mode_flags = select({
        "@platforms//cpu:ppc32": [
            "-static",
            "-mrelocatable",
            "-Wl,-e,_start",
        ],
        "//conditions:default": ["-shared"],
    })
    runtime_libs = select({
        "@platforms//cpu:ppc32": ["-lgcc"],
        "//conditions:default": [],
    })

    _pic_blob_link(
        name = name,
        archive = ":" + lib_name,
        linker_script = linker_script,
        link_mode_flags = link_mode_flags,
        linkopts = _FREESTANDING_LINK_FLAGS + linkopts,
        runtime_libs = runtime_libs,
        **shared_kwargs
    )

def blob_collection(name, blobs, **kwargs):
    """Collects multiple blob .so targets into a single filegroup."""
    native.filegroup(
        name = name,
        srcs = blobs,
        **kwargs
    )
