"""Custom Bazel rules for building PIC blobs as shared objects.

The blob pipeline is:
  1. cc_library      -> object files (.a archive)
  2. genrule (gcc)   -> .so (shared object with custom linker script)
  3. blob_stage      -> copies .so into python/picblobs/_blobs/{os}/{arch}/

We use a genrule instead of cc_binary for linking because cc_binary
injects -Wl,-S (strip) which removes the .text and .rodata sections
we need pyelftools to read at runtime.

Because the genrule bypasses cc_common.link, it does NOT inherit the
toolchain `freestanding` feature's link flags. The freestanding link
flags (-nostdlib -nostartfiles -Wl,--gc-sections) are added explicitly
below.
"""

load("@rules_cc//cc:defs.bzl", "cc_library")
load("//bazel:platforms.bzl", "BLOB_TARGETS")  # @unused (re-exported)

# Re-export BLOB_TARGETS from the generated platforms.bzl so existing
# consumers of blob.bzl continue to work. The canonical source is
# bazel/platforms.bzl (generated by tools/generate.py from registry.py).

# Attribute names that are legal on both cc_library and genrule. Anything
# in **kwargs that isn't in this set is routed only to cc_library.
_SHARED_KWARGS = (
    "tags",
    "visibility",
    "testonly",
    "compatible_with",
    "target_compatible_with",
    "exec_compatible_with",
    "restricted_to",
    "features",
)

def _split_kwargs(kwargs):
    """Return (shared_kwargs, library_only_kwargs)."""
    shared = {}
    library_only = {}
    for key, value in kwargs.items():
        if key in _SHARED_KWARGS:
            shared[key] = value
        else:
            library_only[key] = value
    return shared, library_only

def _link_mode_flags_command():
    """Returns a shell fragment that selects the final blob link mode."""
    return "\n".join([
        'triple="$$($(CC) -dumpmachine)"',
        "link_mode='-shared'",
        "runtime_libs=''",
        'case "$$triple" in',
        "  powerpc-*)",
        "    # PPC32 blobs work reliably as static relocatable ELFs.",
        "    link_mode='-static -mrelocatable -Wl,-e,_start'",
        "    runtime_libs='-lgcc'",
        "    ;;",
        "esac",
    ])

def _target_os_defines():
    """Return per-target-OS compile defines selected from platform constraints."""
    return select({
        "//platforms:is_target_linux": ["PICBLOBS_OS_LINUX"],
        "//platforms:is_target_freebsd": ["PICBLOBS_OS_FREEBSD"],
        "//platforms:is_target_windows": ["PICBLOBS_OS_WINDOWS"],
        "//conditions:default": [],
    })

def _target_abi_copts():
    """Return ABI-specific compile flags selected from platform constraints."""
    return select({
        "//platforms:is_target_windows_aarch64": ["-ffixed-x18"],
        "//conditions:default": [],
    })

# Link flags equivalent to the toolchain's `freestanding` feature flag_set
# for link actions. Kept in sync with toolchains/bootlin.bzl and
# toolchains/arm_none_eabi.bzl.
_FREESTANDING_LINK_FLAGS = [
    "-nostdlib",
    "-nostartfiles",
    "-Wl,--gc-sections",
]

def pic_blob(
        name,
        srcs,
        deps = None,
        hdrs = None,
        linker_script = None,
        copts = None,
        local_defines = None,
        linkopts = None,
        **kwargs):
    """Compile and link a PIC blob as a shared object.

    Creates:
      - {name}_obj : cc_library with the blob source
      - {name}     : genrule that links the .so

    Args:
        name: Blob type name (e.g., "hello", "alloc_jump").
        srcs: C source files.
        deps: cc_library dependencies.
        hdrs: Header files.
        linker_script: Label for the custom linker script.
        copts: Additional C compiler flags.
        local_defines: Preprocessor defines (e.g., ["PIC_PLATFORM_HOSTED"]).
        linkopts: Additional linker flags (added to the genrule link command).
        **kwargs: Common attributes (tags, visibility, etc.) forwarded to
            both the cc_library and the genrule. Anything that is not a
            shared attribute is routed only to the cc_library.
    """
    deps = deps or []
    hdrs = hdrs or []
    copts = (copts or []) + _target_abi_copts()
    local_defines = (local_defines or []) + _target_os_defines()
    linkopts = linkopts or []
    lib_name = name + "_obj"

    shared_kwargs, library_kwargs = _split_kwargs(kwargs)

    cc_library(
        name = lib_name,
        srcs = srcs,
        hdrs = hdrs,
        copts = copts,
        local_defines = local_defines,
        deps = deps,
        **dict(shared_kwargs, **library_kwargs)
    )

    linker_script_flag = ""
    srcs_list = [":" + lib_name]
    if linker_script:
        linker_script_flag = "-T$(location {})".format(linker_script)
        srcs_list.append(linker_script)

    extra_linkopts = " ".join(_FREESTANDING_LINK_FLAGS + linkopts)

    native.genrule(
        name = name,
        srcs = srcs_list,
        outs = [name + ".so"],
        cmd = "\n".join([
            "set -eu",
            _link_mode_flags_command(),
            " ".join([
                "$(CC)",
                "$$link_mode",
                linker_script_flag,
                "-Wl,--whole-archive",
                "$(location :{})".format(lib_name),
                "-Wl,--no-whole-archive",
                extra_linkopts,
                "$$runtime_libs",
                "-o $@",
            ]),
        ]),
        toolchains = ["@rules_cc//cc:current_cc_toolchain"],
        **shared_kwargs
    )

def blob_collection(name, blobs, **kwargs):
    """Collects multiple blob .so targets into a single filegroup."""
    native.filegroup(
        name = name,
        srcs = blobs,
        **kwargs
    )
