"""Custom Bazel rules for building PIC blobs as shared objects.

The blob pipeline is:
  1. cc_library      → object files (.a archive)
  2. genrule (gcc)   → .so (shared object with custom linker script)
  3. blob_stage      → copies .so into python/picblobs/_blobs/{os}/{arch}/

We use a genrule instead of cc_binary for linking because cc_binary
injects -Wl,-S (strip) which removes the .text and .rodata sections
we need pyelftools to read at runtime.
"""

load("@rules_cc//cc:defs.bzl", "cc_library")
load("//bazel:platforms.bzl", "BLOB_TARGETS")  # @unused (re-exported)

# Re-export BLOB_TARGETS from the generated platforms.bzl so existing
# consumers of blob.bzl continue to work. The canonical source is
# bazel/platforms.bzl (generated by tools/generate.py from registry.py).

def pic_blob(
        name,
        srcs,
        deps = None,
        hdrs = None,
        linker_script = None,
        copts = None,
        local_defines = None,
        linkopts = None,
        **kwargs):
    """Compile and link a PIC blob as a shared object.

    Creates:
      - {name}_obj : cc_library with the blob source
      - {name}     : genrule that links the .so

    Args:
        name: Blob type name (e.g., "hello", "alloc_jump").
        srcs: C source files.
        deps: cc_library dependencies.
        hdrs: Header files.
        linker_script: Label for the custom linker script.
        copts: Additional C compiler flags.
        local_defines: Preprocessor defines (e.g., ["PIC_PLATFORM_HOSTED"]).
        linkopts: Additional linker flags.
        **kwargs: Passed through to generated targets.
    """
    deps = deps or []
    hdrs = hdrs or []
    copts = copts or []
    local_defines = local_defines or []
    linkopts = linkopts or []
    lib_name = name + "_obj"

    cc_library(
        name = lib_name,
        srcs = srcs,
        hdrs = hdrs,
        copts = copts,
        local_defines = local_defines,
        deps = deps,
        **kwargs
    )

    linker_script_flag = ""
    srcs_list = [":" + lib_name]
    if linker_script:
        linker_script_flag = "-T$(location {})".format(linker_script)
        srcs_list.append(linker_script)

    extra_linkopts = " ".join(linkopts)

    native.genrule(
        name = name,
        srcs = srcs_list,
        outs = [name + ".so"],
        cmd = " ".join([
            "$(CC)",
            "-nostdlib",
            "-nostartfiles",
            "-shared",
            linker_script_flag,
            "-Wl,--whole-archive",
            "$(location :{})".format(lib_name),
            "-Wl,--no-whole-archive",
            extra_linkopts,
            "-o $@",
        ]),
        toolchains = ["@rules_cc//cc:current_cc_toolchain"],
        **kwargs
    )

def blob_collection(name, blobs, **kwargs):
    """Collects multiple blob .so targets into a single filegroup."""
    native.filegroup(
        name = name,
        srcs = blobs,
        **kwargs
    )
