# Generated by tools/generate.py from tools/registry.py — DO NOT EDIT.

"""Platform target map — single source of truth for OS/arch combinations.

Loaded by blob.bzl and other rules that need the full platform matrix.
"""

BLOB_TARGETS = {
    "linux:x86_64": "//platforms:linux_x86_64",
    "linux:i686": "//platforms:linux_i686",
    "linux:aarch64": "//platforms:linux_aarch64",
    "linux:armv5_arm": "//platforms:linux_armv5_arm",
    "linux:armv5_thumb": "//platforms:linux_armv5_thumb",
    "linux:armv7_thumb": "//platforms:linux_armv7_thumb",
    "linux:s390x": "//platforms:linux_s390x",
    "linux:mipsel32": "//platforms:linux_mipsel32",
    "linux:mipsbe32": "//platforms:linux_mipsbe32",
    "freebsd:x86_64": "//platforms:freebsd_x86_64",
    "freebsd:i686": "//platforms:freebsd_i686",
    "freebsd:aarch64": "//platforms:freebsd_aarch64",
    "freebsd:armv5_arm": "//platforms:freebsd_armv5_arm",
    "freebsd:armv5_thumb": "//platforms:freebsd_armv5_thumb",
    "freebsd:armv7_thumb": "//platforms:freebsd_armv7_thumb",
    "freebsd:mipsel32": "//platforms:freebsd_mipsel32",
    "freebsd:mipsbe32": "//platforms:freebsd_mipsbe32",
    "windows:x86_64": "//platforms:windows_x86_64",
    "windows:i686": "//platforms:windows_i686",
    "windows:aarch64": "//platforms:windows_aarch64",
}
