[pytest]
testpaths =
    python/tests
    python_cli/tests
norecursedirs =
    .git
    .venv
    .pytest_cache
    .ruff_cache
    bazel-bin
    bazel-out
    bazel-testlogs
    bazel-pic
    bazel-workspace
    dist
    build
addopts = --import-mode=importlib
