/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/*
 * picblobs/picblobs.h — single include for blob authors.
 *
 * Usage:
 *   #include "picblobs/os/linux.h"     // select target OS
 *   #include "picblobs/picblobs.h"     // everything else
 */

#ifndef PICBLOBS_PICBLOBS_H
#define PICBLOBS_PICBLOBS_H

#include "picblobs/arch.h"
#include "picblobs/reloc.h"
#include "picblobs/section.h"
#include "picblobs/syscall.h"
#include "picblobs/types.h"

/* Syscall wrappers (each self-contained with numbers + function). */
#include "picblobs/sys/accept.h"
#include "picblobs/sys/bind.h"
#include "picblobs/sys/close.h"
#include "picblobs/sys/connect.h"
#include "picblobs/sys/dup2.h"
#include "picblobs/sys/exit.h"
#include "picblobs/sys/exit_group.h"
#include "picblobs/sys/fstat.h"
#include "picblobs/sys/listen.h"
#include "picblobs/sys/llseek.h"
#include "picblobs/sys/lseek.h"
#include "picblobs/sys/mmap.h"
#include "picblobs/sys/mprotect.h"
#include "picblobs/sys/munmap.h"
#include "picblobs/sys/open.h"
#include "picblobs/sys/pipe.h"
#include "picblobs/sys/read.h"
#include "picblobs/sys/setsockopt.h"
#include "picblobs/sys/socket.h"
#include "picblobs/sys/write.h"

#endif /* PICBLOBS_PICBLOBS_H */
