/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/*
 * picblobs/syscall.h — architecture-portable syscall interface.
 *
 * Dispatches to per-architecture implementations in picblobs/syscall/.
 * To add a new architecture: create picblobs/syscall/{name}.h with
 * pic_raw_syscall(), add to registry.py, run generate.py.
 */

#ifndef PICBLOBS_SYSCALL_H
#define PICBLOBS_SYSCALL_H

#include "picblobs/types.h"

/*
 * Per-architecture pic_raw_syscall() — one file per unique GCC define.
 * Signature: long pic_raw_syscall(long number, long a0..a5)
 */

#if defined(__x86_64__)
#include "picblobs/syscall/x86_64.h"

#elif defined(__i386__)
#include "picblobs/syscall/i386.h"

#elif defined(__aarch64__)
#include "picblobs/syscall/aarch64.h"

#elif defined(__arm__)
#include "picblobs/syscall/arm.h"

#elif defined(__mips__)
#include "picblobs/syscall/mips.h"

#elif defined(__s390x__)
#include "picblobs/syscall/s390x.h"

#else
#error "Unsupported architecture for pic_raw_syscall — add picblobs/syscall/{arch}.h"
#endif

/* Convenience wrappers. */
#define pic_syscall0(n)                     pic_raw_syscall((n), 0, 0, 0, 0, 0, 0)
#define pic_syscall1(n, a)                  pic_raw_syscall((n), (long)(a), 0, 0, 0, 0, 0)
#define pic_syscall2(n, a, b)               pic_raw_syscall((n), (long)(a), (long)(b), 0, 0, 0, 0)
#define pic_syscall3(n, a, b, c)            pic_raw_syscall((n), (long)(a), (long)(b), (long)(c), 0, 0, 0)
#define pic_syscall4(n, a, b, c, d)         pic_raw_syscall((n), (long)(a), (long)(b), (long)(c), (long)(d), 0, 0)
#define pic_syscall5(n, a, b, c, d, e)      pic_raw_syscall((n), (long)(a), (long)(b), (long)(c), (long)(d), (long)(e), 0)
#define pic_syscall6(n, a, b, c, d, e, f)   pic_raw_syscall((n), (long)(a), (long)(b), (long)(c), (long)(d), (long)(e), (long)(f))

#endif /* PICBLOBS_SYSCALL_H */
