#!/bin/bash
#
# build_blobs.sh — Build Cortex-M4 PIC blobs via Bazel and convert to C arrays.
#
# Uses the hermetic arm-none-eabi toolchain managed by Bazel. The blobs
# are compiled with PIC_PLATFORM_HOSTED for the cortexm4_baremetal platform.
#
# Usage:
#   cd mbed && ./build_blobs.sh
#
set -euo pipefail

PROJ_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$(cd "$(dirname "$0")" && pwd)/blobs"

echo "=== Building Cortex-M4 hosted blobs via Bazel ==="

# Build and capture Bazel's output to get exact artifact paths.
BUILD_LOG="$(cd "$PROJ_ROOT" && bazel build //tests:nacl_blobs_cortexm4 2>&1)"
echo "$BUILD_LOG"

# Parse the server .so path from Bazel output (the canonical path).
SERVER_SO="$(echo "$BUILD_LOG" | grep 'nacl_server_hosted\.so$' | awk '{print $NF}')"
CLIENT_SO="$(echo "$BUILD_LOG" | grep 'nacl_client_hosted\.so$' | awk '{print $NF}')"

if [ -z "$SERVER_SO" ] || [ -z "$CLIENT_SO" ]; then
    echo "ERROR: Could not parse blob paths from Bazel output."
    exit 1
fi

# Paths are relative to PROJ_ROOT (Bazel workspace).
SERVER_SO="$PROJ_ROOT/$SERVER_SO"
CLIENT_SO="$PROJ_ROOT/$CLIENT_SO"

echo "Server blob: $SERVER_SO"
echo "Client blob: $CLIENT_SO"

# Get objcopy from the Bazel-managed arm-none-eabi toolchain.
BAZEL_OUTPUT="$(cd "$PROJ_ROOT" && bazel info output_base 2>/dev/null)"
OBJCOPY="$(find "$BAZEL_OUTPUT/external" -name "arm-none-eabi-objcopy" 2>/dev/null | head -1)"
if [ -z "$OBJCOPY" ]; then
    echo "ERROR: arm-none-eabi-objcopy not found in Bazel external repos."
    exit 1
fi
echo "Using objcopy: $OBJCOPY"

mkdir -p "$OUT"

convert_blob() {
    local name="$1"
    local so="$2"
    local bin="$OUT/${name}.bin"
    local hdr="$OUT/${name}_blob.h"
    local varname="${name}_blob"

    echo "--- Converting $name ---"

    "$OBJCOPY" -O binary "$so" "$bin"

    {
        echo "/* Auto-generated by build_blobs.sh — do not edit. */"
        echo "#ifndef ${varname^^}_H"
        echo "#define ${varname^^}_H"
        echo "static const unsigned char ${varname}[] = {"
        xxd -i < "$bin" | sed 's/^/    /'
        echo "};"
        local size
        size=$(wc -c < "$bin")
        echo "static const unsigned int ${varname}_len = ${size};"
        echo "#endif"
    } > "$hdr"

    echo "  $bin: $(wc -c < "$bin") bytes"
    echo "  $hdr: generated"
}

convert_blob nacl_server "$SERVER_SO"
convert_blob nacl_client "$CLIENT_SO"

echo ""
echo "=== Done. Blob headers in $OUT/ ==="
echo "Now run: mbed compile -m NUCLEO_F429ZI -t GCC_ARM"
