/*
 * main.cpp — Mbed OS 5.15 runner for NaCl PIC blobs.
 *
 * Connects to Ethernet, initializes the platform vtable, and
 * launches a PIC blob (server or client) from an embedded C array.
 *
 * Build:
 *   mbed deploy && mbed compile -m NUCLEO_F429ZI -t GCC_ARM
 *
 * Config (mbed_app.json):
 *   "blob_role": "server" or "client"
 */

#include "mbed.h"
#include "EthernetInterface.h"
#include "platform_mbed.h"

/* Blob binaries — generated by build_blobs.sh (xxd -i). */
#include "blobs/nacl_server_blob.h"
#include "blobs/nacl_client_blob.h"

int main()
{
	printf("\r\n=== NaCl PIC blob runner (Mbed OS 5.15) ===\r\n");

	/* Bring up Ethernet with DHCP. */
	EthernetInterface eth;
	nsapi_error_t err = eth.connect();
	if (err != NSAPI_ERROR_OK) {
		printf("Ethernet connect failed: %d\r\n", err);
		return 1;
	}
	printf("IP: %s\r\n", eth.get_ip_address());

	/* Initialize platform vtable. */
	struct pic_platform plat;
	mbed_platform_init(&plat, &eth);

	/* Select blob based on config. */
	const char *role = MBED_CONF_APP_BLOB_ROLE;
	printf("Role: %s\r\n", role);

	if (strcmp(role, "server") == 0) {
		printf("Launching NaCl server blob (%u bytes)...\r\n",
		       (unsigned)nacl_server_blob_len);
		mbed_run_blob(nacl_server_blob, nacl_server_blob_len, &plat);
	} else if (strcmp(role, "client") == 0) {
		printf("Launching NaCl client blob (%u bytes)...\r\n",
		       (unsigned)nacl_client_blob_len);
		mbed_run_blob(nacl_client_blob, nacl_client_blob_len, &plat);
	} else {
		printf("Unknown role: %s (set blob_role in mbed_app.json)\r\n",
		       role);
	}

	while (1)
		__WFI();
}
