"""Blob extraction and loading.

Two loading paths:

1. **Release path** (default): Load from pre-extracted .bin + .json sidecar
   files generated by tools/extract_release.py. No runtime dependencies
   beyond the standard library.

2. **Development path**: Extract directly from .so ELF files using pyelftools.
   Requires pyelftools (optional dependency). Used for local development
   when working with freshly-built .so files.
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
from pathlib import Path


@dataclasses.dataclass(frozen=True)
class BlobData:
    """Extracted blob bytes and metadata."""

    code: bytes
    """Flat code bytes from __blob_start to __blob_end."""

    config_offset: int
    """Offset of __config_start relative to __blob_start."""

    entry_offset: int
    """Offset of the entry point (normally 0)."""

    blob_type: str
    """Blob type identifier (e.g., 'hello')."""

    target_os: str
    """Target operating system (e.g., 'linux')."""

    target_arch: str
    """Target architecture (e.g., 'x86_64')."""

    sha256: str
    """SHA-256 hex digest of the code bytes."""

    sections: dict[str, tuple[int, int]]
    """Section name -> (offset_from_blob_start, size)."""


# ============================================================
# Release path: load from .bin + .json sidecar
# ============================================================


def load_from_sidecar(bin_path: str | Path, json_path: str | Path) -> BlobData:
    """Load a blob from a pre-extracted .bin file and its sidecar .json.

    This is the primary runtime loading path. No ELF parsing required.

    The sidecar JSON is trusted — config_offset, section offsets, and sizes
    are not validated against the code length. The build tooling
    (tools/extract_release.py) is the single source of truth for sidecar
    correctness, and the SHA-256 integrity check guards against corruption.

    Args:
        bin_path: Path to the flat binary .bin file.
        json_path: Path to the sidecar .json metadata file.

    Returns:
        BlobData with code bytes and metadata from the sidecar.

    Raises:
        FileNotFoundError: If either file does not exist.
        ValueError: If the sidecar JSON is malformed or hash mismatch.
    """
    bin_path = Path(bin_path)
    json_path = Path(json_path)

    code = bin_path.read_bytes()
    meta = json.loads(json_path.read_text())

    # Verify integrity.
    actual_sha = hashlib.sha256(code).hexdigest()
    expected_sha = meta.get("sha256", "")
    if actual_sha != expected_sha:
        raise ValueError(
            f"SHA-256 mismatch for {bin_path}: "
            f"expected {expected_sha[:16]}..., got {actual_sha[:16]}..."
        )

    # Convert sections from sidecar format {name: {offset, size, perm}}
    # to BlobData format {name: (offset, size)} for backward compatibility.
    sections: dict[str, tuple[int, int]] = {}
    for name, info in meta.get("sections", {}).items():
        if isinstance(info, dict):
            sections[name] = (info["offset"], info["size"])
        else:
            # Already a tuple/list (shouldn't happen, but be safe).
            sections[name] = (int(info[0]), int(info[1]))

    try:
        return BlobData(
            code=code,
            config_offset=meta["config_offset"],
            entry_offset=meta.get("entry_offset", 0),
            blob_type=meta["type"],
            target_os=meta["os"],
            target_arch=meta["arch"],
            sha256=actual_sha,
            sections=sections,
        )
    except KeyError as e:
        raise ValueError(f"Sidecar JSON missing required field: {e}") from e


# ============================================================
# Development path: extract from .so ELF (requires pyelftools)
# ============================================================


def extract(
    so_path: str | Path,
    blob_type: str = "",
    target_os: str = "",
    target_arch: str = "",
) -> BlobData:
    """Extract flat blob bytes and metadata from a .so file.

    Requires pyelftools. This function is for development use — extracting
    from locally-built .so files. The release package uses load_from_sidecar()
    instead.

    Args:
        so_path: Path to the .so blob file.
        blob_type: Blob type override. If empty, derived from filename.
        target_os: Target OS override. If empty, derived from path.
        target_arch: Target arch override. If empty, derived from path.

    Returns:
        BlobData with extracted code bytes and metadata.

    Raises:
        ImportError: If pyelftools is not installed.
        ValueError: If required symbols or sections are missing.
        FileNotFoundError: If so_path does not exist.
    """
    try:
        from elftools.elf.elffile import ELFFile
    except ImportError:
        raise ImportError(
            "pyelftools is required for extract(). "
            "Install with: pip install 'picblobs[elf]'"
        ) from None

    so_path = Path(so_path)

    # Derive blob_type/os/arch from path if not provided.
    # Expected layout: .../_blobs/{os}/{arch}/{blob_type}.so
    if not blob_type or not target_os or not target_arch:
        parts = so_path.parts
        if len(parts) >= 3:
            if not target_arch:
                target_arch = parts[-2]
            if not target_os:
                target_os = parts[-3]
        if not blob_type:
            blob_type = so_path.stem

    with open(so_path, "rb") as f:
        elf = ELFFile(f)

        symtab = elf.get_section_by_name(".symtab")
        if symtab is None:
            raise ValueError(f"No .symtab in {so_path}")

        syms = _find_symbols(symtab, {"__blob_start", "__blob_end", "__config_start"})
        blob_start = syms["__blob_start"]
        blob_end = syms["__blob_end"]
        config_start = syms["__config_start"]

        code_buf, sections = _extract_blob_data(elf, blob_start, blob_end)
        code = bytes(code_buf)

    return BlobData(
        code=code,
        config_offset=config_start - blob_start,
        entry_offset=0,
        blob_type=blob_type,
        target_os=target_os,
        target_arch=target_arch,
        sha256=hashlib.sha256(code).hexdigest(),
        sections=sections,
    )


def _find_symbols(symtab: "SymbolTableSection", names: set[str]) -> dict[str, int]:
    """Return values for all requested symbols in a single pass."""
    result: dict[str, int] = {}
    for sym in symtab.iter_symbols():
        if sym.name in names:
            result[sym.name] = sym.entry.st_value
            if len(result) == len(names):
                break
    missing = names - result.keys()
    if missing:
        raise ValueError(f"Symbols not found in .symtab: {', '.join(sorted(missing))}")
    return result


def _extract_blob_data(
    elf: "ELFFile",
    start: int,
    end: int,
) -> tuple[bytearray, dict[str, tuple[int, int]]]:
    """Read blob bytes and collect section metadata in a single pass."""
    size = end - start
    buf = bytearray(size)
    sections: dict[str, tuple[int, int]] = {}

    for section in elf.iter_sections():
        sh_flags = section.header.sh_flags
        sh_addr = section.header.sh_addr
        sh_size = section.header.sh_size
        sh_type = section.header.sh_type
        name = section.name

        if not (sh_flags & 0x2):  # SHF_ALLOC
            continue
        if sh_size == 0:
            continue

        sec_start = sh_addr
        sec_end = sh_addr + sh_size
        overlap_start = max(sec_start, start)
        overlap_end = min(sec_end, end)

        if overlap_start >= overlap_end:
            continue

        if name and sec_start >= start and sec_start < end:
            sections[name] = (sec_start - start, sh_size)

        buf_offset = overlap_start - start
        if sh_type == "SHT_NOBITS":
            pass
        else:
            data = section.data()
            data_offset = overlap_start - sec_start
            length = overlap_end - overlap_start
            buf[buf_offset : buf_offset + length] = data[
                data_offset : data_offset + length
            ]

    return buf, sections
