"""Blob sidecar loading.

Runtime code loads pre-extracted ``.bin`` files plus JSON sidecars generated by
``tools/extract_release.py``. ELF ``.so`` parsing is intentionally build-time
only so the installed package and source checkout use the same data format.
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
from pathlib import Path


@dataclasses.dataclass(frozen=True)
class BlobData:
    """Extracted blob bytes and metadata."""

    code: bytes
    """Flat code bytes from __blob_start to __blob_end."""

    config_offset: int
    """Offset of __config_start relative to __blob_start."""

    entry_offset: int
    """Offset of the entry point (normally 0)."""

    blob_type: str
    """Blob type identifier (e.g., 'hello')."""

    target_os: str
    """Target operating system (e.g., 'linux')."""

    target_arch: str
    """Target architecture (e.g., 'x86_64')."""

    sha256: str
    """SHA-256 hex digest of the code bytes."""

    sections: dict[str, tuple[int, int]]
    """Section name -> (offset_from_blob_start, size)."""


def load_from_sidecar(bin_path: str | Path, json_path: str | Path) -> BlobData:
    """Load a blob from a pre-extracted .bin file and its sidecar .json.

    This is the primary runtime loading path. No ELF parsing required.

    The sidecar JSON is trusted — config_offset, section offsets, and sizes
    are not validated against the code length. The build tooling
    (tools/extract_release.py) is the single source of truth for sidecar
    correctness, and the SHA-256 integrity check guards against corruption.

    Args:
        bin_path: Path to the flat binary .bin file.
        json_path: Path to the sidecar .json metadata file.

    Returns:
        BlobData with code bytes and metadata from the sidecar.

    Raises:
        FileNotFoundError: If either file does not exist.
        ValueError: If the sidecar JSON is malformed or hash mismatch.
    """
    bin_path = Path(bin_path)
    json_path = Path(json_path)

    code = bin_path.read_bytes()
    meta = json.loads(json_path.read_text())

    # Verify integrity.
    actual_sha = hashlib.sha256(code).hexdigest()
    expected_sha = meta.get("sha256", "")
    if actual_sha != expected_sha:
        raise ValueError(
            f"SHA-256 mismatch for {bin_path}: "
            f"expected {expected_sha[:16]}..., got {actual_sha[:16]}..."
        )

    # Convert sections from sidecar format {name: {offset, size, perm}}
    # to BlobData format {name: (offset, size)} for backward compatibility.
    sections: dict[str, tuple[int, int]] = {}
    for name, info in meta.get("sections", {}).items():
        if isinstance(info, dict):
            sections[name] = (info["offset"], info["size"])
        else:
            # Already a tuple/list (shouldn't happen, but be safe).
            sections[name] = (int(info[0]), int(info[1]))

    try:
        return BlobData(
            code=code,
            config_offset=meta["config_offset"],
            entry_offset=meta.get("entry_offset", 0),
            blob_type=meta["type"],
            target_os=meta["os"],
            target_arch=meta["arch"],
            sha256=actual_sha,
            sections=sections,
        )
    except KeyError as e:
        raise ValueError(f"Sidecar JSON missing required field: {e}") from e
