/* _start — MIPS o32: extract argc/argv from kernel stack, call runner_main. */
__asm__(".section .text._start,\"ax\"\n"
	".globl _start\n"
	".ent _start\n"
	"_start:\n"
	"  .set noreorder\n"
	"  bal 1f\n"
	"  nop\n"
	"1: .cpload $ra\n"
	"  lw $a0, 0($sp)\n"
	"  addiu $a1, $sp, 4\n"
	"  addiu $sp, $sp, -32\n"
	"  sw $ra, 28($sp)\n"
	"  la $t9, runner_main\n"
	"  jalr $t9\n"
	"  nop\n"
	"  move $a0, $v0\n"
	"  li $v0, 4246\n"
	"  syscall\n"
	"  .set reorder\n"
	".end _start\n");
