/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/accept.h — pic_accept() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_ACCEPT_H
#define PICBLOBS_SYS_ACCEPT_H

#include "picblobs/types.h"

#ifdef PIC_PLATFORM_HOSTED
#include "picblobs/platform.h"
static inline long pic_accept(int sockfd, void *addr, void *addrlen)
{
	return __pic_plat->accept(sockfd, addr, addrlen);
}
#else /* !PIC_PLATFORM_HOSTED */

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_accept 30

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_accept 43
#elif defined(__i386__)
#define __NR_accept 364
#elif defined(__aarch64__)
#define __NR_accept 202
#elif defined(__arm__)
#define __NR_accept 285
#elif defined(__mips__)
#define __NR_accept 4168
#elif defined(__s390x__)
#define __NR_accept 364
#elif defined(__sparc__)
#define __NR_accept 99
#else
#error "Unsupported architecture for pic_accept()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_accept() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/accept.h"
#endif

/* --- Wrapper --- */
static inline long pic_accept(int sockfd, void *addr, void *addrlen)
{
	return pic_syscall3(__NR_accept, sockfd, (long)addr, (long)addrlen);
}

#endif /* !PIC_PLATFORM_HOSTED */
#endif /* PICBLOBS_SYS_ACCEPT_H */
