/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/bind.h — pic_bind() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_BIND_H
#define PICBLOBS_SYS_BIND_H

#include "picblobs/types.h"

#ifdef PIC_PLATFORM_HOSTED
#include "picblobs/platform.h"
static inline long pic_bind(int sockfd, const void *addr, pic_size_t addrlen) {
	return __pic_plat->bind(sockfd, addr, addrlen);
}
#else /* !PIC_PLATFORM_HOSTED */

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_bind             104

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_bind             49
#elif defined(__i386__)
#define __NR_bind             361
#elif defined(__aarch64__)
#define __NR_bind             200
#elif defined(__arm__)
#define __NR_bind             282
#elif defined(__mips__)
#define __NR_bind             4169
#elif defined(__s390x__)
#define __NR_bind             361
#else
#error "Unsupported architecture for pic_bind()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_bind() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/bind.h"
#endif

/* --- Wrapper --- */
static inline long pic_bind(int sockfd, const void *addr, pic_size_t addrlen) {
    return pic_syscall3(__NR_bind, sockfd, (long)addr, addrlen);
}

#endif /* !PIC_PLATFORM_HOSTED */
#endif /* PICBLOBS_SYS_BIND_H */
