/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/close.h — pic_close() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_CLOSE_H
#define PICBLOBS_SYS_CLOSE_H

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_close 6

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_close 3
#elif defined(__i386__)
#define __NR_close 6
#elif defined(__aarch64__)
#define __NR_close 57
#elif defined(__arm__)
#define __NR_close 6
#elif defined(__mips__)
#define __NR_close 4006
#elif defined(__s390x__)
#define __NR_close 6
#else
#error "Unsupported architecture for pic_close()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_close() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/close.h"
#endif

/* --- Wrapper --- */
static inline long pic_close(int fd) { return pic_syscall1(__NR_close, fd); }

#endif /* PICBLOBS_SYS_CLOSE_H */
