/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/connect.h — pic_connect() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_CONNECT_H
#define PICBLOBS_SYS_CONNECT_H

#include "picblobs/types.h"

#ifdef PIC_PLATFORM_HOSTED
#include "picblobs/platform.h"
static inline long pic_connect(int sockfd, const void *addr, pic_size_t addrlen)
{
	return __pic_plat->connect(sockfd, addr, addrlen);
}
#else /* !PIC_PLATFORM_HOSTED */

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_connect 98

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__powerpc64__)
#define __NR_connect 328
#elif defined(__aarch64__)
#define __NR_connect 203
#elif defined(__powerpc__)
#define __NR_connect 328
#elif defined(__x86_64__)
#define __NR_connect 42
#elif defined(__s390x__)
#define __NR_connect 362
#elif defined(__sparc__)
#define __NR_connect 98
#elif defined(__i386__)
#define __NR_connect 362
#elif defined(__mips__)
#define __NR_connect 4170
#elif defined(__arm__)
#define __NR_connect 283
#elif defined(__riscv)
#define __NR_connect 203
#else
#error "Unsupported architecture for pic_connect()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_connect() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/connect.h"
#endif

/* --- Wrapper --- */
static inline long pic_connect(int sockfd, const void *addr, pic_size_t addrlen)
{
	return pic_syscall3(__NR_connect, sockfd, (long)addr, addrlen);
}

#endif /* !PIC_PLATFORM_HOSTED */
#endif /* PICBLOBS_SYS_CONNECT_H */
