/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/dup2.h — pic_dup2() syscall. */
/* Supported: linux */

#ifndef PICBLOBS_SYS_DUP2_H
#define PICBLOBS_SYS_DUP2_H

#include "picblobs/types.h"

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#error "pic_dup2() is not available on freebsd"

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_dup2             33
#elif defined(__i386__)
#define __NR_dup2             63
#elif defined(__arm__)
#define __NR_dup2             63
#elif defined(__s390x__)
#define __NR_dup2             63
#else
#error "Unsupported architecture for pic_dup2()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_dup2() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/dup2.h"
#endif

/* --- Wrapper --- */
static inline long pic_dup2(int oldfd, int newfd) {
    return pic_syscall2(__NR_dup2, oldfd, newfd);
}
#endif /* PICBLOBS_SYS_DUP2_H */
