/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/exit.h — pic_exit() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_EXIT_H
#define PICBLOBS_SYS_EXIT_H

#include "picblobs/types.h"

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_exit 1

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_exit 60
#elif defined(__i386__)
#define __NR_exit 1
#elif defined(__aarch64__)
#define __NR_exit 93
#elif defined(__arm__)
#define __NR_exit 1
#elif defined(__mips__)
#define __NR_exit 4001
#elif defined(__s390x__)
#define __NR_exit 1
#elif defined(__sparc__)
#define __NR_exit 1
#else
#error "Unsupported architecture for pic_exit()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_exit() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/exit.h"
#endif

/* --- Wrapper --- */
__attribute__((noreturn)) static inline void pic_exit(int code)
{
	pic_syscall1(__NR_exit, code);
	__builtin_unreachable();
}
#endif /* PICBLOBS_SYS_EXIT_H */
