/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/exit_group.h — pic_exit_group() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_EXIT_GROUP_H
#define PICBLOBS_SYS_EXIT_GROUP_H

#include "picblobs/types.h"

#ifdef PIC_PLATFORM_HOSTED
#include "picblobs/platform.h"
__attribute__((noreturn))
static inline void pic_exit_group(int code) {
	__pic_plat->exit_group(code);
	__builtin_unreachable();
}
#else /* !PIC_PLATFORM_HOSTED */

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_exit_group       431

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_exit_group       231
#elif defined(__i386__)
#define __NR_exit_group       252
#elif defined(__aarch64__)
#define __NR_exit_group       94
#elif defined(__arm__)
#define __NR_exit_group       248
#elif defined(__mips__)
#define __NR_exit_group       4246
#elif defined(__s390x__)
#define __NR_exit_group       248
#else
#error "Unsupported architecture for pic_exit_group()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_exit_group() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/exit_group.h"
#endif

/* --- Wrapper --- */
__attribute__((noreturn))
static inline void pic_exit_group(int code) {
    pic_syscall1(__NR_exit_group, code);
    __builtin_unreachable();
}

#endif /* !PIC_PLATFORM_HOSTED */
#endif /* PICBLOBS_SYS_EXIT_GROUP_H */
