/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/fstat.h — pic_fstat() syscall. */
/* Supported: linux */

#ifndef PICBLOBS_SYS_FSTAT_H
#define PICBLOBS_SYS_FSTAT_H

#include "picblobs/types.h"

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#error "pic_fstat() is not available on freebsd"

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_fstat            5
#elif defined(__i386__)
#define __NR_fstat            108
#elif defined(__arm__)
#define __NR_fstat            108
#elif defined(__s390x__)
#define __NR_fstat            108
#else
#error "Unsupported architecture for pic_fstat()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_fstat() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/fstat.h"
#endif

/* --- Wrapper --- */
static inline long pic_fstat(int fd, void *statbuf) {
    return pic_syscall2(__NR_fstat, fd, (long)statbuf);
}
#endif /* PICBLOBS_SYS_FSTAT_H */
