/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/listen.h — pic_listen() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_LISTEN_H
#define PICBLOBS_SYS_LISTEN_H

#include "picblobs/types.h"

#ifdef PIC_PLATFORM_HOSTED
#include "picblobs/platform.h"
static inline long pic_listen(int sockfd, int backlog)
{
	return __pic_plat->listen(sockfd, backlog);
}
#else /* !PIC_PLATFORM_HOSTED */

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_listen 106

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_listen 50
#elif defined(__i386__)
#define __NR_listen 363
#elif defined(__aarch64__)
#define __NR_listen 201
#elif defined(__arm__)
#define __NR_listen 284
#elif defined(__mips__)
#define __NR_listen 4174
#elif defined(__s390x__)
#define __NR_listen 363
#elif defined(__sparc__)
#define __NR_listen 354
#else
#error "Unsupported architecture for pic_listen()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_listen() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/listen.h"
#endif

/* --- Wrapper --- */
static inline long pic_listen(int sockfd, int backlog)
{
	return pic_syscall2(__NR_listen, sockfd, backlog);
}

#endif /* !PIC_PLATFORM_HOSTED */
#endif /* PICBLOBS_SYS_LISTEN_H */
