/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/listen.h — pic_listen() syscall. */
/* Supported: linux */

#ifndef PICBLOBS_SYS_LISTEN_H
#define PICBLOBS_SYS_LISTEN_H

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#error "pic_listen() is not available on freebsd"

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_listen 50
#elif defined(__s390x__)
#define __NR_listen 363
#else
#error "Unsupported architecture for pic_listen()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_listen() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/listen.h"
#endif

/* --- Wrapper --- */
static inline long pic_listen(int sockfd, int backlog)
{
	return pic_syscall2(__NR_listen, sockfd, backlog);
}

#endif /* PICBLOBS_SYS_LISTEN_H */
