/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/llseek.h — pic_llseek() syscall. */
/* Supported: linux */

#ifndef PICBLOBS_SYS_LLSEEK_H
#define PICBLOBS_SYS_LLSEEK_H

#include "picblobs/types.h"

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#error "pic_llseek() is not available on freebsd"

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__i386__)
#define __NR_llseek           140
#elif defined(__arm__)
#define __NR_llseek           140
#elif defined(__mips__)
#define __NR_llseek           4140
#else
#error "Unsupported architecture for pic_llseek()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_llseek() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/llseek.h"
#endif

/* --- Wrapper --- */
static inline long pic_llseek(int fd, unsigned long offset_high, unsigned long offset_low, void *result, unsigned int whence) {
    return pic_syscall5(__NR_llseek, fd, offset_high, offset_low, (long)result, whence);
}
#endif /* PICBLOBS_SYS_LLSEEK_H */
