/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/lseek.h — pic_lseek() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_LSEEK_H
#define PICBLOBS_SYS_LSEEK_H

#include "picblobs/types.h"

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_lseek 478

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_lseek 8
#elif defined(__i386__)
#define __NR_llseek 140
#define __NR_lseek 19
#elif defined(__aarch64__)
#define __NR_lseek 62
#elif defined(__arm__)
#define __NR_llseek 140
#define __NR_lseek 19
#elif defined(__mips__)
#define __NR_llseek 4140
#define __NR_lseek 4019
#elif defined(__s390x__)
#define __NR_lseek 19
#elif defined(__sparc__)
#define __NR_llseek 236
#define __NR_lseek 19
#else
#error "Unsupported architecture for pic_lseek()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_lseek() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/lseek.h"
#endif

/* --- Constants --- */
#define PIC_SEEK_SET 0
#define PIC_SEEK_CUR 1
#define PIC_SEEK_END 2

/* --- Wrapper --- */
static inline long pic_lseek(int fd, long offset, int whence)
{
	return pic_syscall3(__NR_lseek, fd, offset, whence);
}
#endif /* PICBLOBS_SYS_LSEEK_H */
