/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/mmap.h — pic_mmap() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_MMAP_H
#define PICBLOBS_SYS_MMAP_H

#include "picblobs/types.h"

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_mmap 477

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__powerpc64__)
#define __NR_mmap 90
#elif defined(__aarch64__)
#define __NR_mmap 222
#elif defined(__powerpc__)
#define __NR_mmap 192
#elif defined(__x86_64__)
#define __NR_mmap 9
#elif defined(__s390x__)
#define __NR_mmap 90
#elif defined(__sparc__)
#define __NR_mmap 56
#elif defined(__i386__)
#define __NR_mmap 192
#elif defined(__mips__)
#define __NR_mmap 4210
#elif defined(__arm__)
#define __NR_mmap 192
#elif defined(__riscv)
#define __NR_mmap 222
#else
#error "Unsupported architecture for pic_mmap()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_mmap() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/mmap.h"
#endif

/* mmap flags */
#if defined(PICBLOBS_OS_LINUX) && defined(__mips__)
#define PIC_MAP_SHARED 0x001
#define PIC_MAP_PRIVATE 0x002
#define PIC_MAP_FIXED 0x010
#define PIC_MAP_ANONYMOUS 0x800
#elif defined(PICBLOBS_OS_FREEBSD)
#define PIC_MAP_SHARED 0x0001
#define PIC_MAP_PRIVATE 0x0002
#define PIC_MAP_FIXED 0x0010
#define PIC_MAP_ANONYMOUS 0x1000
#else
#define PIC_MAP_SHARED 0x01
#define PIC_MAP_PRIVATE 0x02
#define PIC_MAP_FIXED 0x10
#define PIC_MAP_ANONYMOUS 0x20
#endif

/* --- Wrapper --- */
#define _PIC_MMAP2_SHIFT 12

static inline void *pic_mmap(
	void *addr, pic_size_t len, int prot, int flags, int fd, long offset)
{
#if PIC_ARCH_USES_OLD_MMAP
	/* s390x old_mmap: args passed via struct pointer in r2. */
	unsigned long args[6] = {(unsigned long)addr, (unsigned long)len,
		(unsigned long)prot, (unsigned long)flags, (unsigned long)fd,
		(unsigned long)offset};
	return (void *)pic_syscall1(__NR_mmap, (long)args);
#elif PIC_ARCH_USES_MMAP2
	return (void *)pic_syscall6(__NR_mmap, (long)addr, len, prot, flags, fd,
		offset >> _PIC_MMAP2_SHIFT);
#else
	return (void *)pic_syscall6(
		__NR_mmap, (long)addr, len, prot, flags, fd, offset);
#endif
}
#endif /* PICBLOBS_SYS_MMAP_H */
