/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/munmap.h — pic_munmap() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_MUNMAP_H
#define PICBLOBS_SYS_MUNMAP_H

#include "picblobs/types.h"

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_munmap 73

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_munmap 11
#elif defined(__i386__)
#define __NR_munmap 91
#elif defined(__aarch64__)
#define __NR_munmap 215
#elif defined(__arm__)
#define __NR_munmap 91
#elif defined(__mips__)
#define __NR_munmap 4091
#elif defined(__s390x__)
#define __NR_munmap 91
#else
#error "Unsupported architecture for pic_munmap()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_munmap() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/munmap.h"
#endif

/* --- Wrapper --- */
static inline long pic_munmap(void *addr, pic_size_t len)
{
	return pic_syscall2(__NR_munmap, (long)addr, len);
}
#endif /* PICBLOBS_SYS_MUNMAP_H */
