/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/pipe.h — pic_pipe() syscall. */
/* Supported: linux */

#ifndef PICBLOBS_SYS_PIPE_H
#define PICBLOBS_SYS_PIPE_H

#include "picblobs/types.h"

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#error "pic_pipe() is not available on freebsd"

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_pipe 22
#elif defined(__i386__)
#define __NR_pipe 42
#elif defined(__arm__)
#define __NR_pipe 42
#elif defined(__s390x__)
#define __NR_pipe 42
#else
#error "Unsupported architecture for pic_pipe()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_pipe() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/pipe.h"
#endif

/* --- Wrapper --- */
static inline long pic_pipe(int *pipefd)
{
	return pic_syscall1(__NR_pipe, (long)pipefd);
}
#endif /* PICBLOBS_SYS_PIPE_H */
