/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/read.h — pic_read() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_READ_H
#define PICBLOBS_SYS_READ_H

#include "picblobs/types.h"

#ifdef PIC_PLATFORM_HOSTED
#include "picblobs/platform.h"
static inline long pic_read(int fd, void *buf, pic_size_t count) {
	return __pic_plat->read(fd, buf, count);
}
#else /* !PIC_PLATFORM_HOSTED */

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_read             3

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_read             0
#elif defined(__i386__)
#define __NR_read             3
#elif defined(__aarch64__)
#define __NR_read             63
#elif defined(__arm__)
#define __NR_read             3
#elif defined(__mips__)
#define __NR_read             4003
#elif defined(__s390x__)
#define __NR_read             3
#else
#error "Unsupported architecture for pic_read()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_read() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/read.h"
#endif

/* --- Wrapper --- */
static inline long pic_read(int fd, void *buf, pic_size_t count) {
    return pic_syscall3(__NR_read, fd, (long)buf, count);
}

#endif /* !PIC_PLATFORM_HOSTED */
#endif /* PICBLOBS_SYS_READ_H */
