/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/setsockopt.h — pic_setsockopt() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_SETSOCKOPT_H
#define PICBLOBS_SYS_SETSOCKOPT_H

#include "picblobs/types.h"

#ifdef PIC_PLATFORM_HOSTED
#include "picblobs/platform.h"
static inline long pic_setsockopt(int sockfd, int level, int optname,
	const void *optval, pic_size_t optlen)
{
	return __pic_plat->setsockopt(sockfd, level, optname, optval, optlen);
}
#else /* !PIC_PLATFORM_HOSTED */

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_setsockopt 105

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__powerpc64__)
#define __NR_setsockopt 339
#elif defined(__aarch64__)
#define __NR_setsockopt 208
#elif defined(__powerpc__)
#define __NR_setsockopt 339
#elif defined(__x86_64__)
#define __NR_setsockopt 54
#elif defined(__s390x__)
#define __NR_setsockopt 366
#elif defined(__sparc__)
#define __NR_setsockopt 355
#elif defined(__i386__)
#define __NR_setsockopt 366
#elif defined(__mips__)
#define __NR_setsockopt 4181
#elif defined(__arm__)
#define __NR_setsockopt 294
#elif defined(__riscv)
#define __NR_setsockopt 208
#else
#error "Unsupported architecture for pic_setsockopt()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_setsockopt() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/setsockopt.h"
#endif

/* --- Wrapper --- */
static inline long pic_setsockopt(int sockfd, int level, int optname,
	const void *optval, pic_size_t optlen)
{
	return pic_syscall5(
		__NR_setsockopt, sockfd, level, optname, (long)optval, optlen);
}

#endif /* !PIC_PLATFORM_HOSTED */
#endif /* PICBLOBS_SYS_SETSOCKOPT_H */
