/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/setsockopt.h — pic_setsockopt() syscall. */
/* Supported: linux */

#ifndef PICBLOBS_SYS_SETSOCKOPT_H
#define PICBLOBS_SYS_SETSOCKOPT_H

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#error "pic_setsockopt() is not available on freebsd"

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_setsockopt 54
#elif defined(__s390x__)
#define __NR_setsockopt 366
#else
#error "Unsupported architecture for pic_setsockopt()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_setsockopt() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/setsockopt.h"
#endif

/* --- Wrapper --- */
static inline long pic_setsockopt(int sockfd, int level, int optname,
	const void *optval, pic_size_t optlen)
{
	return pic_syscall5(
		__NR_setsockopt, sockfd, level, optname, (long)optval, optlen);
}

#endif /* PICBLOBS_SYS_SETSOCKOPT_H */
