/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/socket.h — pic_socket() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_SOCKET_H
#define PICBLOBS_SYS_SOCKET_H

#include "picblobs/types.h"

#ifdef PIC_PLATFORM_HOSTED
#include "picblobs/platform.h"
static inline long pic_socket(int domain, int type, int protocol) {
	return __pic_plat->socket(domain, type, protocol);
}
#else /* !PIC_PLATFORM_HOSTED */

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_socket           97

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_socket           41
#elif defined(__i386__)
#define __NR_socket           359
#elif defined(__aarch64__)
#define __NR_socket           198
#elif defined(__arm__)
#define __NR_socket           281
#elif defined(__mips__)
#define __NR_socket           4183
#elif defined(__s390x__)
#define __NR_socket           359
#else
#error "Unsupported architecture for pic_socket()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_socket() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/socket.h"
#endif

/* --- Wrapper --- */
static inline long pic_socket(int domain, int type, int protocol) {
    return pic_syscall3(__NR_socket, domain, type, protocol);
}

#endif /* !PIC_PLATFORM_HOSTED */
#endif /* PICBLOBS_SYS_SOCKET_H */
