/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */
/* picblobs/sys/write.h — pic_write() syscall. */
/* Supported: freebsd, linux */

#ifndef PICBLOBS_SYS_WRITE_H
#define PICBLOBS_SYS_WRITE_H

#include "picblobs/types.h"

#ifdef PIC_PLATFORM_HOSTED
#include "picblobs/platform.h"
static inline long pic_write(int fd, const void *buf, pic_size_t count)
{
	return __pic_plat->write(fd, buf, count);
}
#else /* !PIC_PLATFORM_HOSTED */

#include "picblobs/arch.h"
#include "picblobs/syscall.h"

/* --- Syscall numbers --- */

#if defined(PICBLOBS_OS_FREEBSD)

#define __NR_write 4

#elif defined(PICBLOBS_OS_LINUX)

#if defined(__x86_64__)
#define __NR_write 1
#elif defined(__i386__)
#define __NR_write 4
#elif defined(__aarch64__)
#define __NR_write 64
#elif defined(__arm__)
#define __NR_write 4
#elif defined(__mips__)
#define __NR_write 4004
#elif defined(__s390x__)
#define __NR_write 4
#elif defined(__sparc__)
#define __NR_write 4
#else
#error "Unsupported architecture for pic_write()"
#endif

#elif defined(PICBLOBS_OS_WINDOWS)

#error "pic_write() is not available on windows"

#else
#error "No target OS defined — #include picblobs/os/{os}.h before sys/write.h"
#endif

/* --- Wrapper --- */
static inline long pic_write(int fd, const void *buf, pic_size_t count)
{
	return pic_syscall3(__NR_write, fd, (long)buf, count);
}

#endif /* !PIC_PLATFORM_HOSTED */
#endif /* PICBLOBS_SYS_WRITE_H */
