#!/usr/bin/env python3
"""Generate ALL derived files from the canonical registry.

This is the single codegen entry point. Every file it generates is
marked with a DO NOT EDIT header. Adding a new architecture, OS, or
syscall should NEVER require modifying a generated file.

Generated files:
  C headers:
    - src/include/picblobs/arch.h
    - src/include/picblobs/syscall.h          (dispatcher → per-arch files)
    - src/include/picblobs/picblobs.h         (auto-discovers sys/*.h)
    - src/include/picblobs/sys/{os}/nr.h      (for each OS in registry)

  Bazel:
    - platforms/BUILD.bazel
    - toolchains/BUILD.bazel

  Config:
    - .bazelrc  (platform config block between markers)

  C test runners:
    - tests/runners/{os}/runner.c             (dispatcher → per-arch start/*.h)

Usage:
    python tools/generate.py              # generate all
    python tools/generate.py --check      # exit 1 if any file is stale
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from registry import (
    ARCHITECTURES,
    LINKER_SYMBOLS,
    MMAP_FLAGS,
    OPERATING_SYSTEMS,
    SYSCALL_DEFS,
    SYSCALL_NUMBERS,
    SyscallDef,
    all_platforms,
    all_syscall_names,
    gcc_defines,
    syscall_os_support,
)

sys.path.pop(0)

PROJECT_ROOT = Path(__file__).resolve().parent.parent

_C = "/* Generated by tools/generate.py from tools/registry.py — DO NOT EDIT. */\n"
_BZL = "# Generated by tools/generate.py from tools/registry.py — DO NOT EDIT.\n"


# ============================================================
# Helpers
# ============================================================


def _sorted_gcc_defines() -> list[str]:
    """Return gcc defines in a stable order for #if/#elif chains."""
    # Use insertion order from ARCHITECTURES (deterministic).
    seen: list[str] = []
    for arch in ARCHITECTURES.values():
        if arch.gcc_define not in seen:
            seen.append(arch.gcc_define)
    return seen


def _clang_format(content: str) -> str:
    """Run clang-format on content if available. Returns formatted content."""
    import shutil

    if not shutil.which("clang-format"):
        return content
    try:
        result = subprocess.run(
            [
                "clang-format",
                f"--assume-filename={PROJECT_ROOT}/x.c",
                f"--style=file:{PROJECT_ROOT}/.clang-format",
            ],
            input=content,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return result.stdout
    except Exception:
        pass
    return content


def _write(path: Path, content: str, check: bool) -> bool:
    """Write content to path. Returns True if file changed.

    C/H files are run through clang-format before writing.
    """
    if path.suffix in (".c", ".h"):
        content = _clang_format(content)
    if path.exists() and path.read_text() == content:
        return False
    if check:
        print(f"  OUT OF DATE: {path.relative_to(PROJECT_ROOT)}")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  wrote {path.relative_to(PROJECT_ROOT)}")
    return True


# ============================================================
# C: arch.h — generated from registry traits
# ============================================================


def _gen_arch_h() -> str:
    lines = [
        _C,
        textwrap.dedent("""\
        /*
         * picblobs/arch.h — architecture trait flags.
         *
         * Centralizes all per-architecture boolean decisions into named traits.
         * Other headers check traits (e.g., PIC_ARCH_USES_MMAP2) instead of
         * raw architecture macros.
         *
         * To add a new architecture: add an entry to tools/registry.py,
         * then run: python tools/generate.py
         */

        #ifndef PICBLOBS_ARCH_H
        #define PICBLOBS_ARCH_H
        """),
    ]

    trait_names = [
        "uses_mmap2",
        "uses_old_mmap",
        "openat_only",
        "needs_got_reloc",
        "needs_trampoline",
        "is_32bit",
    ]
    trait_macros = {t: f"PIC_ARCH_{t.upper()}" for t in trait_names}

    defines = _sorted_gcc_defines()
    for i, gcc_define in enumerate(defines):
        # Find the first arch with this define (for name/bits).
        arch = next(a for a in ARCHITECTURES.values() if a.gcc_define == gcc_define)
        prefix = "#if" if i == 0 else "#elif"
        lines.append(f"{prefix} defined({gcc_define})\n")
        lines.append(f'#define PIC_ARCH_NAME            "{arch.name.split("_")[0]}"\n')
        lines.append(
            f"#define PIC_ARCH_BITS            {64 if not arch.is_32bit else 32}\n"
        )
        for trait in trait_names:
            if getattr(arch, trait, False):
                lines.append(f"#define {trait_macros[trait]:<28s} 1\n")
        lines.append("\n")

    lines.append(
        textwrap.dedent("""\
        #else
        #error "Unsupported architecture — add to tools/registry.py and run generate.py"
        #endif

        /* Default trait values for architectures that don't set them. */
        """)
    )
    for trait in trait_names:
        macro = trait_macros[trait]
        lines.append(f"#ifndef {macro}\n#define {macro:<28s} 0\n#endif\n")

    lines.append("\n#endif /* PICBLOBS_ARCH_H */\n")
    return "".join(lines)


# ============================================================
# C: syscall.h — generated dispatcher to per-arch files
# ============================================================


def _gen_syscall_h() -> str:
    lines = [
        _C,
        textwrap.dedent("""\
        /*
         * picblobs/syscall.h — architecture-portable syscall interface.
         *
         * Dispatches to per-architecture implementations in picblobs/syscall/.
         * To add a new architecture: create picblobs/syscall/{name}.h with
         * pic_raw_syscall(), add to registry.py, run generate.py.
         */

        #ifndef PICBLOBS_SYSCALL_H
        #define PICBLOBS_SYSCALL_H

        #include "picblobs/types.h"

        /*
         * Per-architecture pic_raw_syscall() — one file per unique GCC define.
         * Signature: long pic_raw_syscall(long number, long a0..a5)
         */

        """),
    ]

    defines = _sorted_gcc_defines()
    # Map gcc_define to the file stem (strip underscores).
    define_to_file = {}
    for arch in ARCHITECTURES.values():
        if arch.gcc_define not in define_to_file:
            # __x86_64__ → x86_64, __i386__ → i386, __arm__ → arm, __mips__ → mips
            stem = arch.gcc_define.strip("_")
            define_to_file[arch.gcc_define] = stem

    for i, gcc_define in enumerate(defines):
        prefix = "#if" if i == 0 else "#elif"
        stem = define_to_file[gcc_define]
        lines.append(f"{prefix} defined({gcc_define})\n")
        lines.append(f'#include "picblobs/syscall/{stem}.h"\n\n')

    lines.append(
        textwrap.dedent("""\
        #else
        #error "Unsupported architecture for pic_raw_syscall — add picblobs/syscall/{arch}.h"
        #endif

        /* Convenience wrappers. */
        #define pic_syscall0(n)                     pic_raw_syscall((n), 0, 0, 0, 0, 0, 0)
        #define pic_syscall1(n, a)                  pic_raw_syscall((n), (long)(a), 0, 0, 0, 0, 0)
        #define pic_syscall2(n, a, b)               pic_raw_syscall((n), (long)(a), (long)(b), 0, 0, 0, 0)
        #define pic_syscall3(n, a, b, c)            pic_raw_syscall((n), (long)(a), (long)(b), (long)(c), 0, 0, 0)
        #define pic_syscall4(n, a, b, c, d)         pic_raw_syscall((n), (long)(a), (long)(b), (long)(c), (long)(d), 0, 0)
        #define pic_syscall5(n, a, b, c, d, e)      pic_raw_syscall((n), (long)(a), (long)(b), (long)(c), (long)(d), (long)(e), 0)
        #define pic_syscall6(n, a, b, c, d, e, f)   pic_raw_syscall((n), (long)(a), (long)(b), (long)(c), (long)(d), (long)(e), (long)(f))

        #endif /* PICBLOBS_SYSCALL_H */
        """)
    )
    return "".join(lines)


# ============================================================
# C: picblobs.h — auto-discovers sys/*.h wrappers
# ============================================================


def _gen_picblobs_h() -> str:
    sys_dir = PROJECT_ROOT / "src/include/picblobs/sys"
    wrappers = sorted(
        f.name
        for f in sys_dir.glob("*.h")
        if f.name != "constants.h"  # not a syscall wrapper
    )

    # picblobs.h now includes syscall.h (for the primitive) but NOT
    # individual sys/*.h wrappers — those require an OS header first.
    # The blob author includes: os/{os}.h + picblobs.h, OR os/{os}.h + individual sys/*.h.
    syscall_names = sorted(SYSCALL_DEFS.keys())
    includes = "\n".join(f'#include "picblobs/sys/{n}.h"' for n in syscall_names)
    return textwrap.dedent(f"""\
        {_C}/*
         * picblobs/picblobs.h — single include for blob authors.
         *
         * Usage:
         *   #include "picblobs/os/linux.h"     // select target OS
         *   #include "picblobs/picblobs.h"     // everything else
         */

        #ifndef PICBLOBS_PICBLOBS_H
        #define PICBLOBS_PICBLOBS_H

        #include "picblobs/arch.h"
        #include "picblobs/types.h"
        #include "picblobs/syscall.h"
        #include "picblobs/section.h"
        #include "picblobs/reloc.h"

        /* Syscall wrappers (each self-contained with numbers + function). */
        {includes}

        #endif /* PICBLOBS_PICBLOBS_H */
    """)


# ============================================================
# C: sys/{name}.h — one self-contained file per syscall
# ============================================================


def _gen_syscall_header(sdef: SyscallDef) -> str:
    """Generate a complete sys/{name}.h with numbers + wrapper."""
    guard = f"PICBLOBS_SYS_{sdef.name.upper()}_H"
    os_support = syscall_os_support(sdef.name)
    supported_oses = sorted(os_support.keys())

    lines: list[str] = [_C]
    lines.append(f"/* picblobs/sys/{sdef.name}.h — {sdef.wrapper}() syscall. */\n")
    lines.append(f"/* Supported: {', '.join(supported_oses)} */\n\n")
    lines.append(f"#ifndef {guard}\n#define {guard}\n\n")
    lines.append(f'#include "picblobs/types.h"\n\n')

    # Hosted-mode path: delegate to pic_platform vtable.
    if sdef.hosted_call:
        lines.append("#ifdef PIC_PLATFORM_HOSTED\n")
        lines.append('#include "picblobs/platform.h"\n')
        attrs = ""
        if sdef.noreturn:
            attrs = "__attribute__((noreturn))\n"
        lines.append(
            f"{attrs}static inline {sdef.return_type} {sdef.wrapper}({sdef.params}) {{\n"
        )
        if sdef.return_type == "void":
            lines.append(f"\t{sdef.hosted_call};\n")
            if sdef.noreturn:
                lines.append("\t__builtin_unreachable();\n")
        else:
            lines.append(f"\treturn {sdef.hosted_call};\n")
        lines.append("}\n")
        lines.append("#else /* !PIC_PLATFORM_HOSTED */\n\n")

    lines.append(f'#include "picblobs/arch.h"\n')
    lines.append(f'#include "picblobs/syscall.h"\n\n')

    # --- OS dispatch + per-arch numbers ---
    # Collect all __NR_ names this syscall needs (for open: open + openat).
    nr_names_needed: set[str] = set()
    for os_name, arch_nrs in os_support.items():
        for key in arch_nrs:
            if key == "_all_":
                nr_names_needed.add(sdef.name)
            else:
                # The key in the table might differ from sdef.name
                # (e.g., open has "openat" on aarch64).
                # Look up what's actually in the table.
                pass
        # Collect actual nr names from the OS tables.
        if "_all_" in arch_nrs:
            nr_names_needed.add(sdef.name)
        else:
            for gcc_define, _ in arch_nrs.items():
                # Check if this arch defines this syscall under a different name.
                os_table = SYSCALL_NUMBERS[os_name]
                for name in os_table.get(gcc_define, {}):
                    if name == sdef.name or name in _related_nr_names(sdef.name):
                        nr_names_needed.add(name)

    lines.append("/* --- Syscall numbers --- */\n\n")

    related = _related_nr_names(sdef.name)
    all_oses = sorted(OPERATING_SYSTEMS.keys())
    first_os = True
    for os_name in all_oses:
        os_macro = f"PICBLOBS_OS_{os_name.upper()}"
        prefix = "#if" if first_os else "#elif"
        lines.append(f"{prefix} defined({os_macro})\n\n")

        if os_name not in os_support:
            lines.append(f'#error "{sdef.wrapper}() is not available on {os_name}"\n\n')
        else:
            arch_nrs = os_support[os_name]
            if "_all_" in arch_nrs:
                nr = arch_nrs["_all_"]
                lines.append(f"#define __NR_{sdef.name:<16s} {nr}\n\n")
            else:
                # Per-architecture: emit all __NR_ defines this arch needs.
                defines = _sorted_gcc_defines()
                os_tables = SYSCALL_NUMBERS.get(os_name, {})
                first_arch = True
                for gcc_define in defines:
                    arch_table = os_tables.get(gcc_define, {})
                    # Collect all related __NR_ defines for this arch.
                    nr_defs: list[tuple[str, int]] = []
                    for name in sorted(related):
                        if name in arch_table:
                            nr_defs.append((name, arch_table[name]))
                    if nr_defs:
                        aprefix = "#if" if first_arch else "#elif"
                        lines.append(f"{aprefix} defined({gcc_define})\n")
                        for name, nr in nr_defs:
                            lines.append(f"#define __NR_{name:<16s} {nr}\n")
                        first_arch = False
                if not first_arch:
                    lines.append("#else\n")
                    lines.append(
                        f'#error "Unsupported architecture for {sdef.wrapper}()"\n'
                    )
                    lines.append("#endif\n\n")

        first_os = False

    lines.append("#else\n")
    lines.append(
        f'#error "No target OS defined — #include picblobs/os/{{os}}.h before sys/{sdef.name}.h"\n'
    )
    lines.append("#endif\n\n")

    # --- Constants ---
    if sdef.constants:
        lines.append("/* --- Constants --- */\n")
        lines.append(sdef.constants + "\n\n")

    # Special: mmap flags are arch+OS-specific.
    if sdef.name == "mmap":
        lines.append("/* mmap flags */\n")
        lines.append("#if defined(PICBLOBS_OS_LINUX) && defined(__mips__)\n")
        for flag in ("MAP_SHARED", "MAP_PRIVATE", "MAP_FIXED", "MAP_ANONYMOUS"):
            val = MMAP_FLAGS[flag].get("__mips__", MMAP_FLAGS[flag]["_default_"])
            lines.append(f"#define PIC_{flag:<16s} {val:#05x}\n")
        lines.append("#elif defined(PICBLOBS_OS_FREEBSD)\n")
        for flag in ("MAP_SHARED", "MAP_PRIVATE", "MAP_FIXED", "MAP_ANONYMOUS"):
            val = MMAP_FLAGS[flag].get("freebsd", MMAP_FLAGS[flag]["_default_"])
            lines.append(f"#define PIC_{flag:<16s} {val:#06x}\n")
        lines.append("#else\n")
        for flag in ("MAP_SHARED", "MAP_PRIVATE", "MAP_FIXED", "MAP_ANONYMOUS"):
            val = MMAP_FLAGS[flag]["_default_"]
            lines.append(f"#define PIC_{flag:<16s} {val:#04x}\n")
        lines.append("#endif\n\n")

    # --- Wrapper function ---
    lines.append("/* --- Wrapper --- */\n")
    if sdef.custom_body:
        lines.append(sdef.custom_body + "\n")
    else:
        attrs = ""
        if sdef.noreturn:
            attrs = "__attribute__((noreturn))\n"
        lines.append(
            f"{attrs}static inline {sdef.return_type} {sdef.wrapper}({sdef.params}) {{\n"
        )
        call = f"pic_syscall{sdef.arg_count}(__NR_{sdef.name}, {sdef.call_args})"
        if sdef.return_type == "void":
            lines.append(f"    {call};\n")
            if sdef.noreturn:
                lines.append("    __builtin_unreachable();\n")
        elif sdef.return_type == "void *":
            lines.append(f"    return (void *){call};\n")
        else:
            lines.append(f"    return {call};\n")
        lines.append("}\n")

    if sdef.hosted_call:
        lines.append("\n#endif /* !PIC_PLATFORM_HOSTED */\n")
    lines.append(f"#endif /* {guard} */\n")
    return "".join(lines)


def _related_nr_names(syscall_name: str) -> set[str]:
    """Return related __NR_ names for a syscall (e.g., open → openat)."""
    related: dict[str, set[str]] = {
        "open": {"open", "openat"},
        "lseek": {"lseek", "llseek"},
    }
    return related.get(syscall_name, {syscall_name})


# ============================================================
# C: runner.c — generated dispatcher to per-arch start/*.h
# ============================================================


def _gen_runner_c(os_name: str) -> str:
    start_dir = PROJECT_ROOT / "tests/runners" / os_name / "start"
    if not start_dir.exists():
        return ""  # OS runner not yet implemented

    lines = [
        _C,
        textwrap.dedent(f"""\
        /*
         * {os_name.title()} test runner for PIC blobs.
         *
         * Loads a blob binary into an RWX memory region and transfers
         * execution to offset 0. Per-architecture _start stubs live in
         * start/{{arch}}.h — add a new file there for new architectures.
         */

        #include "picblobs/os/{os_name}.h"
        #include "picblobs/sys/read.h"
        #include "picblobs/sys/open.h"
        #include "picblobs/sys/close.h"
        #include "picblobs/sys/lseek.h"
        #include "picblobs/sys/mmap.h"
        #include "picblobs/sys/mprotect.h"
        #include "picblobs/sys/exit.h"
        #include "picblobs/sys/exit_group.h"

        #define RUNNER_ERROR 127

        static long file_size(int fd) {{
            long end = pic_lseek(fd, 0, PIC_SEEK_END);
            if (end < 0) {{
                return -1;
            }}
            if (pic_lseek(fd, 0, PIC_SEEK_SET) < 0) {{
                return -1;
            }}
            return end;
        }}

        static long read_all(int fd, void *buf, pic_size_t count) {{
            pic_u8 *p = (pic_u8 *)buf;
            pic_size_t done = 0;
            while (done < count) {{
                long n = pic_read(fd, p + done, count - done);
                if (n <= 0) {{
                    return -1;
                }}
                done += (pic_size_t)n;
            }}
            return (long)done;
        }}

        /* Per-architecture _start — dispatched to start/{{arch}}.h files. */

        """),
    ]

    # Discover available start/*.h files and map to gcc defines.
    arch_files: list[tuple[str, str]] = []
    for gcc_define in _sorted_gcc_defines():
        stem = gcc_define.strip("_")
        start_file = start_dir / f"{stem}.h"
        if start_file.exists():
            arch_files.append((gcc_define, stem))

    for i, (gcc_define, stem) in enumerate(arch_files):
        prefix = "#if" if i == 0 else "#elif"
        lines.append(f"{prefix} defined({gcc_define})\n")
        lines.append(f'#include "start/{stem}.h"\n\n')

    lines.append(
        textwrap.dedent("""\
        #else
        #error "Unsupported architecture for _start — add start/{arch}.h"
        #endif

        int runner_main(int argc, char **argv) {
            if (argc < 2) {
                pic_exit_group(RUNNER_ERROR);
            }

            int fd = (int)pic_open(argv[1], PIC_O_RDONLY, 0);
            if (fd < 0) {
                pic_exit_group(RUNNER_ERROR);
            }

            long size = file_size(fd);
            if (size <= 0) {
                pic_close(fd);
                pic_exit_group(RUNNER_ERROR);
            }

            void *mem = pic_mmap(
                PIC_NULL, (pic_size_t)size,
                PIC_PROT_READ | PIC_PROT_WRITE | PIC_PROT_EXEC,
                PIC_MAP_PRIVATE | PIC_MAP_ANONYMOUS,
                -1, 0
            );
            if ((long)mem == -1) {
                pic_close(fd);
                pic_exit_group(RUNNER_ERROR);
            }

            if (read_all(fd, mem, (pic_size_t)size) < 0) {
                pic_close(fd);
                pic_exit_group(RUNNER_ERROR);
            }

            pic_close(fd);

            /* On ARM Thumb, function pointers must have bit 0 set to stay
             * in Thumb mode. The mmap'd address is page-aligned (bit 0 = 0),
             * so without this fixup BLX would switch to ARM mode. */
        #ifdef __thumb__
            ((void (*)(void))((pic_uintptr)mem | 1))();
        #else
            ((void (*)(void))mem)();
        #endif

            pic_exit_group(RUNNER_ERROR);
        }
        """)
    )
    return "".join(lines)


# ============================================================
# Bazel: platforms/BUILD.bazel
# ============================================================


def _gen_platforms_build() -> str:
    lines = [_BZL, '\npackage(default_visibility = ["//visibility:public"])\n\n']

    lines.append(
        "# Custom target_os instead of @platforms//os:os — the blob OS is a\n"
        "# cross-compilation target property, not the execution OS. A Linux host\n"
        "# builds FreeBSD and Windows blobs; using @platforms//os would confuse\n"
        "# Bazel's toolchain resolution. This constraint is for blob target selection.\n"
    )
    lines.append('constraint_setting(name = "target_os")\n\n')

    for os_name in OPERATING_SYSTEMS:
        lines.append(
            f'constraint_value(name = "{os_name}", constraint_setting = ":target_os")\n'
        )
    lines.append("\n")

    custom_cpus: set[str] = set()
    for arch in ARCHITECTURES.values():
        if arch.cpu_constraint.startswith("//platforms:"):
            cpu = arch.cpu_constraint.split(":")[-1]
            if cpu not in custom_cpus:
                custom_cpus.add(cpu)
                lines.append(
                    f'constraint_value(name = "{cpu}", '
                    f'constraint_setting = "@platforms//cpu:cpu")\n'
                )
    if custom_cpus:
        lines.append("\n")

    lines.append(
        'constraint_setting(\n    name = "instruction_mode",\n'
        '    default_constraint_value = ":mode_default",\n)\n\n'
    )
    for mode in ("mode_default", "mode_arm", "mode_thumb"):
        lines.append(
            f'constraint_value(name = "{mode}", '
            f'constraint_setting = ":instruction_mode")\n'
        )
    lines.append("\n")

    for os_name, os_def in OPERATING_SYSTEMS.items():
        lines.append(f"# {os_name.title()} ({len(os_def.architectures)})\n")
        for arch_name in os_def.architectures:
            arch = ARCHITECTURES[arch_name]
            mode = (
                ":mode_arm"
                if arch_name == "armv5_arm"
                else ":mode_thumb"
                if arch_name in ("armv5_thumb", "armv7_thumb")
                else ":mode_default"
            )
            name = f"{os_name}_{arch_name}"
            lines.append(
                f'platform(name = "{name}", constraint_values = '
                f'["{arch.cpu_constraint}", ":{os_name}", "{mode}"])\n'
            )
        lines.append("\n")

    # Bare-metal Cortex-M4 (Mbed OS / STM32 hosted-mode blobs).
    lines.append("# Bare-metal constraints (Cortex-M4 / Mbed OS)\n")
    lines.append('constraint_setting(name = "float_abi")\n')
    lines.append(
        'constraint_value(name = "softfloat", constraint_setting = ":float_abi")\n'
    )
    lines.append(
        'constraint_value(name = "hardfloat", constraint_setting = ":float_abi")\n\n'
    )
    lines.append('constraint_setting(name = "runtime")\n')
    lines.append(
        'constraint_value(name = "baremetal", constraint_setting = ":runtime")\n\n'
    )
    lines.append(
        "platform(\n"
        '    name = "cortexm4_baremetal",\n'
        "    constraint_values = [\n"
        '        "@platforms//cpu:arm",\n'
        '        ":baremetal",\n'
        '        ":softfloat",\n'
        "    ],\n"
        ")\n\n"
    )

    return "".join(lines)


# ============================================================
# Bazel: toolchains/BUILD.bazel
# ============================================================


def _gen_toolchains_build() -> str:
    lines = [_BZL, '\npackage(default_visibility = ["//visibility:public"])\n\n']

    # ARM GNU bare-metal toolchain (must be registered before Bootlin ARM
    # so that cortexm4_baremetal resolves to arm_none_eabi, not bootlin_armv5).
    lines.append(
        "toolchain(\n"
        '    name = "arm_none_eabi",\n'
        '    toolchain = "@arm_none_eabi//:cc_toolchain",\n'
        '    toolchain_type = "@rules_cc//cc:toolchain_type",\n'
        "    target_compatible_with = [\n"
        '        "@platforms//cpu:arm",\n'
        '        "//platforms:baremetal",\n'
        "    ],\n"
        ")\n\n"
    )

    seen: set[str] = set()
    for arch in ARCHITECTURES.values():
        if arch.bootlin_arch in seen:
            continue
        seen.add(arch.bootlin_arch)
        tc_name = arch.name
        if tc_name.startswith("armv5_"):
            tc_name = "armv5"
        elif tc_name.startswith("armv7_"):
            tc_name = "armv7"
        lines.append(
            f"toolchain(\n"
            f'    name = "bootlin_{tc_name}",\n'
            f'    toolchain = "@bootlin_{tc_name}//:cc_toolchain",\n'
            f'    toolchain_type = "@rules_cc//cc:toolchain_type",\n'
            f'    target_compatible_with = ["{arch.cpu_constraint}"],\n'
            f")\n\n"
        )
    return "".join(lines)


# ============================================================
# .bazelrc platform configs (injected between markers)
# ============================================================

_MARKER_START = "# BEGIN GENERATED PLATFORM CONFIGS"
_MARKER_END = "# END GENERATED PLATFORM CONFIGS"


def _gen_bazelrc_block() -> str:
    lines = []
    for os_name, os_def in OPERATING_SYSTEMS.items():
        for arch_name in os_def.architectures:
            cfg = f"{os_name}_{arch_name}"
            pad = max(1, 22 - len(cfg))
            lines.append(f"build:{cfg}{' ' * pad}--platforms=//platforms:{cfg}")
        lines.append("")
    return "\n".join(lines)


# ============================================================
# Bazel: bazel/platforms.bzl — BLOB_TARGETS dict
# ============================================================


def _gen_platforms_bzl() -> str:
    lines = [
        _BZL,
        textwrap.dedent("""\

        \"\"\"Platform target map — single source of truth for OS/arch combinations.

        Loaded by blob.bzl and other rules that need the full platform matrix.
        \"\"\"

        BLOB_TARGETS = {
        """),
    ]
    for os_name, os_def in OPERATING_SYSTEMS.items():
        for arch_name in os_def.architectures:
            key = f"{os_name}:{arch_name}"
            val = f"//platforms:{os_name}_{arch_name}"
            lines.append(f'    "{key}": "{val}",\n')
    lines.append("}\n")
    return "".join(lines)


# ============================================================
# Blob auto-discovery: payload BUILD.bazel
# ============================================================


def _blob_needs_hosted(source: Path) -> bool:
    """Check if a blob source uses the hosted platform abstraction."""
    content = source.read_text()
    return "PIC_PLATFORM_HOSTED" in content


def _gen_payload_build() -> str:
    """Generate src/payload/BUILD.bazel by scanning for .c files."""
    payload_dir = PROJECT_ROOT / "src/payload"
    c_files = sorted(f.stem for f in payload_dir.glob("*.c"))
    if not c_files:
        return ""

    # Check which blobs need hosted variants and extract_bin.
    hosted_blobs = [s for s in c_files if _blob_needs_hosted(payload_dir / f"{s}.c")]

    lines = [
        _BZL,
        textwrap.dedent("""\

        load("//bazel:blob.bzl", "pic_blob")
        """),
    ]

    # Only load extract_bin if there are blobs that need it.
    if hosted_blobs:
        lines.append('load("//src/payload:extract.bzl", "extract_bin")\n')

    lines.append(
        textwrap.dedent("""\

        package(default_visibility = ["//visibility:public"])

        """)
    )

    for stem in c_files:
        lines.append(
            textwrap.dedent(f"""\
            pic_blob(
                name = "{stem}",
                srcs = ["{stem}.c"],
                deps = ["//src/include/picblobs:headers"],
                linker_script = "//src/linker:blob.ld",
            )

            """)
        )

        if stem in hosted_blobs:
            lines.append(
                textwrap.dedent(f"""\
                extract_bin(
                    name = "{stem}_bin",
                    src = ":{stem}",
                )

                pic_blob(
                    name = "{stem}_hosted",
                    srcs = ["{stem}.c"],
                    local_defines = ["PIC_PLATFORM_HOSTED"],
                    deps = ["//src/include/picblobs:headers"],
                    linker_script = "//src/linker:blob.ld",
                )

                extract_bin(
                    name = "{stem}_hosted_bin",
                    src = ":{stem}_hosted",
                )

                """)
            )

    return "".join(lines)


# ============================================================
# Main
# ============================================================


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate derived files from registry")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated files are up to date (exit 1 if not)",
    )
    args = parser.parse_args()

    targets: list[tuple[Path, str]] = [
        # C headers
        (PROJECT_ROOT / "src/include/picblobs/arch.h", _gen_arch_h()),
        (PROJECT_ROOT / "src/include/picblobs/syscall.h", _gen_syscall_h()),
        (PROJECT_ROOT / "src/include/picblobs/picblobs.h", _gen_picblobs_h()),
        # Bazel
        (PROJECT_ROOT / "platforms/BUILD.bazel", _gen_platforms_build()),
        (PROJECT_ROOT / "toolchains/BUILD.bazel", _gen_toolchains_build()),
        (PROJECT_ROOT / "bazel/platforms.bzl", _gen_platforms_bzl()),
        # Blob targets
        (PROJECT_ROOT / "src/payload/BUILD.bazel", _gen_payload_build()),
    ]

    # Per-syscall sys/{name}.h files.
    for sdef in SYSCALL_DEFS.values():
        path = PROJECT_ROOT / f"src/include/picblobs/sys/{sdef.name}.h"
        targets.append((path, _gen_syscall_header(sdef)))

    # Per-OS runner.c files.
    # The Windows runner is hand-written (mock TEB/PEB, not a generic loader)
    # and must NOT be overwritten by the generator.
    for os_name in OPERATING_SYSTEMS:
        if os_name == "windows":
            continue
        runner_c = _gen_runner_c(os_name)
        if runner_c:
            path = PROJECT_ROOT / f"tests/runners/{os_name}/runner.c"
            targets.append((path, runner_c))

    any_changed = False
    for path, content in targets:
        if not content:
            continue
        if _write(path, content, args.check):
            any_changed = True

    # .bazelrc: inject between markers.
    bazelrc_path = PROJECT_ROOT / ".bazelrc"
    bazelrc = bazelrc_path.read_text()
    block = f"{_MARKER_START}\n{_gen_bazelrc_block()}{_MARKER_END}"

    if _MARKER_START in bazelrc:
        new_bazelrc = re.sub(
            rf"{re.escape(_MARKER_START)}.*?{re.escape(_MARKER_END)}",
            block,
            bazelrc,
            flags=re.DOTALL,
        )
    else:
        # First run: find platform config lines and replace them.
        lines = bazelrc.split("\n")
        start = end = None
        for i, line in enumerate(lines):
            if re.match(r"build:(linux|freebsd|windows)_", line):
                if start is None:
                    start = i
                end = i
        if start is not None:
            new_bazelrc = "\n".join(lines[:start] + [block] + lines[end + 1 :])
        else:
            new_bazelrc = bazelrc + "\n" + block + "\n"

    if _write(bazelrc_path, new_bazelrc, args.check):
        any_changed = True

    if args.check and any_changed:
        print("\nOut of date. Run: python tools/generate.py")
        return 1
    if not any_changed:
        print("All generated files up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
